/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd_or_nottdd_that_is_the_question;

import lombok.extern.java.Log;

@Log
public class App {
    public static final String HELLO_WORLD = "Hello World!";

    public static void main(String[] args) {
        log.info(HELLO_WORLD);
    }
}
